env:
  auth_log_path: "/Users/ayushrawat/cs/devops/elk/logs/catalina.out"
  vector_log_path: "/Users/ayushrawat/cs/devops/elk/logs/vector.log"
  kafka_log_path: "/Users/ayushrawat/cs/devops/elk/logs/kafka.log"
  state_db_path: "/Users/ayushrawat/cs/java/logit/fluentbit/state/"

service:
  log_level: debug
  flush: 5

pipeline:
  inputs:
    - name: tail
      buffer_chunk_size: 1M
      buffer_max_size: 5M
      read_from_head: true
      path: ${auth_log_path}
      db: ${state_db_path}/auth-state.db
      tag: auth
      key: log
      multiline.parser: auth_multiline_log_parser

    - name: tail
      buffer_chunk_size: 1M
      buffer_max_size: 5M
      read_from_head: true
      path: ${vector_log_path}
      db: ${state_db_path}/vector-state.db
      tag: vector
      key: log
      multiline.parser: vector_multiline_log_parser

    - name: tail
      buffer_chunk_size: 1M
      buffer_max_size: 5M
      read_from_head: true
      path: ${kafka_log_path}
      db: ${state_db_path}/kafka-state.db
      tag: kafka
      key: log
      multiline.parser: auth_multiline_log_parser

  filters:
    - name: parser
      match: auth
      key_name: log
      parser: auth_java_log_parser

    - name: record_modifier
      match: auth
      record:
        - service_name auth

    - name: parser
      match: vector
      key_name: log
      parser: vector_java_log_parser

    - name: record_modifier
      match: vector
      record:
        service_name vector

    - name: parser
      match: kafka
      key_name: log
      parser: auth_java_log_parser

    - name: record_modifier
      match: kafka
      record:
        - service_name kafka

  outputs:
    - name: http
      match: "*"
      host: 127.0.0.1
      port: 3338
      uri: /api/index/fluent
      format: json
      json_date_key: date
      json_date_format: iso8601

multiline_parsers:
  - name: auth_multiline_log_parser
    type: regex
    flush_timeout: 1000
    rules:
      - state: start_state
        regex: "^[A-Z][a-z]{2} [0-9]{2}, [0-9]{4} [0-9]{1,2}:[0-9]{1,2}:[0-9]{1,2} [AP]M"
        next_state: cont
      - state: cont
        regex: "^(?![A-Z][a-z]{2} [0-9]{2}, [0-9]{4} [0-9]{1,2}:[0-9]{1,2}:[0-9]{1,2} [AP]M).*"
        next_state: cont

  - name: vector_multiline_log_parser
    type: regex
    flush_timeout: 1000
    rules:
      - state: start_state
        regex: "^[0-9]{4}-[0-9]{1,2}-[0-9]{1,2}"
        next_state: cont
      - state: cont
        regex: "^(?![0-9]{4}-[0-9]{1,2}-[0-9]{1,2}).*"
        next_state: cont

parsers:
  - name: auth_java_log_parser
    type: regex
    format: regex
    regex: "^(?<timestamp>[A-Z][a-z]{2}\\s*[0-9]{1,2}, [0-9]{4} [0-9]{1,2}:[0-9]{1,2}:[0-9]{1,2} [AP]M)\\s+(?<class>[A-Za-z0-9\\._\\$]+)\\s+(?<method>[^\n]+)\n+(?<level>(INFO|DEBUG|WARN|ERROR|SEVERE|FATAL|TRACE|WARNING)):\\s+(?<msg>[\\s\\S]*)"
    time_key: timestamp

  - name: vector_java_log_parser
    type: regex
    format: regex
    regex: "^(?<timestamp>[0-9-]{10}\\s*[0-9:]{8},[0-9]*)\\s*\\[(?<thread>[a-z-0-9]*)\\]\\s*(?<level>[\\w]*)\\s*-\\s*(?<class>[\\w.]*)\\s*\\((?<method>[\\w.:]*)\\)[\\s|{}]*(?<msg>[\\s\\S]*)"
    time_key: timestamp

#
# References:
#
# configuration: https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/yaml/configuration-file
# input tail: https://docs.fluentbit.io/manual/data-pipeline/inputs/tail
# parsers: https://docs.fluentbit.io/manual/data-pipeline/parsers/configuring-parser
# record modifier: https://docs.fluentbit.io/manual/data-pipeline/filters/record-modifier
#
# multiline parsers: https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/multiline-parsing#parsers_multiline.yaml-2
# multiline rules:  If any line starts with start_state's regex then keep appending un-till cont's regex found
#                   In another words keep appending logs to one big log un-till another timestamp found
#
# Input -> MultiLine -> Parser -> Output
#