### AUTH SEARCH
POST http://localhost:3338/api/search/fluent
Content-Type: application/json
Accept: application/json

{
  "index": "auth",
  "query": "level:error OR message:timeout",
  "topN": 20,
  "fields": [
    "timestamp",
    "message",
    "level",
    "class",
    "method"
  ],
  "stem": true
}

### VECTOR LOG SEACH
POST http://localhost:3338/api/search/fluent
Content-Type: application/json
Accept: application/json

{
  "index": "vector",
  "query": "StitchingFloorPlan",
  "topN": 0,
  "fields": [
    "message"
  ],
  "stem": true
}


### VECTOR ERROR LOGS
POST http://localhost:3338/api/search/fluent
Content-Type: application/json
Accept: application/json

{
  "index": "vector",
  "query": "error",
  "topN": 0,
  "fields": [
    "level"
  ],
  "stem": true
}

### STEMMING TEST
POST http://localhost:3338/api/search/fluent
Content-Type: application/json
Accept: application/json

{
  "index": "auth",
  "query": "populating",
  "topN": 0,
  "fields": [
    "message"
  ],
  "stem": false
}
